baseURL = "https://vksundararajan.github.io/VIBE/"
languageCode = "en-us"
title = "VIBE"
theme = "hugo-bearblog"
enableEmoji = true
canonifyURLs = true
cleanDestinationDir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[params]
  description = "CTF writeups, personal blogs, and hacker notes."
  author = "Vigneshwar Sundararajan"
  github = "https://github.com/vksundararajan"
