baseURL = "https://vgnshwar.github.io/"
languageCode = "en-us"
title = "~Vigneshwar Sundararajan"
theme = "hugo-bearblog"
enableEmoji = true
canonifyURLs = true
cleanDestinationDir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[params]
  description = "CTF writeups, personal blogs, and hacker notes."
  author = "Vigneshwar Sundararajan"
  github = "https://github.com/vgnshwar"

[params.giscus]
  repo = "vgnshwar/vgnshwar.github.io"
  repoID = "R_kgDOOyppBg"
  category = "Announcements"
  categoryID = "DIC_kwDOOyppBs4C-8Ap"
  mapping = "og:title"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "https://vgnshwar.github.io/css/giscus.css"
  lang = "en"
  loading = "lazy"
